name: task5-lisa-taiji
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - numpy=1.26.4
  - scipy=1.13.1
  - matplotlib
  - h5py
  - pandas
  - jupyter
  - notebook
  - ipykernel
  - numba
  - pip
  - pip:
      - bilby==1.0.0
      - corner>=2.2
      - eryn>=1.2
      - dynesty==1.0.1
      - emcee>=3.1
      - nessai>=0.15
      - git+https://github.com/XGI-MSU/WDMWaveletTransforms.git
